export default function UsagePage() {
  return (
    <main class="w-full text-secondary bg-primary">
      <ol class="w-full flex flex-col items-center text-center *:h-svh *:p-4">
        <li>
          <p>
            1.みんなでおなじURL(ルーム)にアクセスします。
          </p>
          <img
            src="/usage-online-play.webp"
            alt="オンラインプレイの説明用画像"
            width="100%"
          />
        </li>
        <li>
          <p>
            2.ツールバーからマスをえらびます。
          </p>
          <img
            src="/usage-making-toolbar.webp"
            alt="ツールバーの説明用画像"
            width="100%"
          />
        </li>
        <li>
          <p>3.ボードをクリックしてマスをおきます。</p>
          <img
            src="/usage-making-board.webp"
            alt="ボードの説明用画像"
            width="100%"
          />
        </li>
        <li>
          <p>4.すごろくができたら「あそぶ！」ボタンをクリックしてください。</p>
          <img
            src="/usage-making-play-button.webp"
            alt="あそぶ！ボタンの説明用画像"
            width="100%"
          />
        </li>
        <li>
          <p>5.「-1」と「+1」ボタンでプレイ人数をえらびます。</p>
          <img
            src="/usage-playing-player-cnt.webp"
            alt="プレイ人数の増やし方と減らし方の説明用画像"
            width="100%"
          />
        </li>
        <li>
          <p>6.「ロール！」ボタンでサイコロがまわりはじめます。</p>
          <img
            src="/usage-playing-roll.webp"
            alt="ロール！ボタンの説明用画像"
            width="100%"
          />
        </li>
        <li>
          <p>7.「とめる！」ボタンで出た目だけプレイヤーがすすみます。</p>
          <img
            src="/usage-playing-stop.webp"
            alt="とめる！ボタンの説明用画像"
            width="100%"
          />
        </li>
        <li>
          <p>8.プレイヤーがゴールするとランキングが表示されます。</p>
          <img
            src="/usage-playing-ranking.webp"
            alt="ランキングの説明用画像"
            width="100%"
          />
        </li>
      </ol>
    </main>
  );
}
